spring:
  liquibase:
    change-log: classpath:db/changelog.xml

  datasource:
    url: jdbc:postgresql://localhost/sayhi_db
    username: postgres
    password: postgres

  artemis:
    mode: embedded
server:
  error:
    include-message: always