spring:
  liquibase:
    change-log: classpath:db/changelog.xml

  datasource:
    url: jdbc:h2:mem:sayhiDB
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  error:
    include-message: always